### PR TITLE
Fix generation script.

### PR DESCRIPTION
**Pull request by mattcollier**
@aljones15 I had to make these changes to get the generation script working on my system.  Does this version work on your system?

### CODE REVIEW

**Comment by aljones15** [comment]
will test shortly

tested on mac osx and your changes break it here. maybe we need to add a check?

**Comment by mattcollier** [comment]
@aljones15 I think I see the problem.

You are using the `withFileTypes` option to `fs.readdirSync
which was introduced in Node 10.10.0.  I'm running node 10.15.3 that includes this feature, and you are running 10.6.0 which does not.

https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options
https://nodejs.org/api/fs.html#fs_class_fs_dirent

```js
const fs = require('fs');
const x = fs.readdirSync('.', {withFileTypes: true});
console.log('OBJECT', x);
console.log('JSON', JSON.stringify(x, null, 2));
```

On node 10.15.3 produces:
```
OBJECT [ Dirent { name: 'fsstuff.js', [Symbol(type)]: 1 },
  Dirent { name: 'muze.js', [Symbol(type)]: 1 },
  Dirent { name: 'plotly-latest.min.js', [Symbol(type)]: 1 } ]
JSON [
  {
    "name": "fsstuff.js"
  },
  {
    "name": "muze.js"
  },
  {
    "name": "plotly-latest.min.js"
  }
]
```

**Comment by aljones15** [comment]
> @aljones15 I think I see the problem.
> 
> You are using the `withFileTypes` option to `fs.readdirSync`
> which was introduced in Node 10.10.0. I'm running node 10.15.3 that includes this feature, and you are running 10.6.0 which does not.
> 
> https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options
> https://nodejs.org/api/fs.html#fs_class_fs_dirent
> 
> ```js
> const fs = require('fs');
> const x = fs.readdirSync('.', {withFileTypes: true});
> console.log('OBJECT', x);
> console.log('JSON', JSON.stringify(x, null, 2));
> ```
> 
> On node 10.15.3 produces:
> 
> ```
> OBJECT [ Dirent { name: 'fsstuff.js', [Symbol(type)]: 1 },
>   Dirent { name: 'muze.js', [Symbol(type)]: 1 },
>   Dirent { name: 'plotly-latest.min.js', [Symbol(type)]: 1 } ]
> JSON [
>   {
>     "name": "fsstuff.js"
>   },
>   {
>     "name": "muze.js"
>   },
>   {
>     "name": "plotly-latest.min.js"
>   }
> ]
> ```

does the update script account for this though?

**Comment by mattcollier** [comment]
If the `{withFileTypes: true}` option is required to make this work, then we need to check node version and throw if that feature is not available.  If it's not required, then we need to remove the option.  Either way, we want consistent results out of `readaddr` so that all the exception handling is not required.

Since the code works on your node version that does not have the `withFileTypes` option, then it seems to me that the option is not required.

**Comment by aljones15** [comment]
@mattcollier I tried with withFileTypes set to both true and false did not make a difference on my mac. I went ahead and removed it. upgraded node to 11.11.0
works here.

**Pull request merged**
