### PR TITLE
Add secp256k1

### PR DESCRIPTION
**Pull request by OR13**
Addresses: https://github.com/digitalbazaar/crypto-ld/issues/42

- Add https://github.com/digitalbazaar/secp256k1-key-pair
- Add some tests (skip failing / not implemented)

We may want to require the skipped tests to be passing, in order to merge this... in which case, this will be blocked pending further updates to:

https://github.com/digitalbazaar/secp256k1-key-pair

### CODE REVIEW

**Comment by dlongley** [comment]
A goal we've adopted for this repo is to keep suites in their own repos but pluggable with this one. That way suites can be installed only as needed, which is particularly important for browser code. Note that we'd like to do the same with the other "built in suites" but there are only so many hours in the day(s).

On that basis, I recommend we close this PR or change it so that it's merely an update to the README that shows how to use secp256k1 with this library (whilst requiring it manually). That's something we could definitely support here.

**Comment by OR13** [comment]
I agree with the goal 100%, but the current README is not structured to support it at all... in fact, it suggest the opposite intention:

https://github.com/digitalbazaar/crypto-ld#generating-a-new-key-pair

It sounds like the following, might be acceptable:

Add an example to the readme for using secp256k1 module for importing an LDKeyPair... like so:

```
const Secp256k1KeyPair = require('secp256k1-key-pair');
const key = Secp256k1KeyPair.generate(options);
const serializedKeyPair = key.export();
const keyPair = await LDKeyPair.from(JSON.parse(serializedKeyPair));
```

Make `secp256k1-key-pair` a dev dependency and keep tests OR

Move tests to `secp256k1-key-pair`....

How do we indend to ensure that the `LDKeyPair` is satisfied?

Should the tests be in the repo, or should the tests be in the key repo?

**Comment by OR13** [comment]
There are 2 places where `const Secp256k1KeyPair = require('secp256k1-key-pair');` is required...

```
/**
   * Creates an instance of LDKeyPair from a key fingerprint.
   * Note: Only key types that use their full public key in the fingerprint
   * are supported (so, currently, only 'ed25519').
   *
   * @param {string} fingerprint
   * @returns {LDKeyPair}
   * @throws Unsupported Fingerprint Type.
   */
  static fromFingerprint({fingerprint}) {
    // skip leading `z` that indicates base58 encoding
    const buffer = base58.decode(fingerprint.substr(1));

    // buffer is: 0xed 0x01 <public key bytes>
    if(buffer[0] === 0xed && buffer[1] === 0x01) {
      const Ed25519KeyPair = require('./Ed25519KeyPair');
      return new Ed25519KeyPair({
        publicKeyBase58: base58.encode(buffer.slice(2))
      });
    }

    // buffer is: 0xe7 0x01 <public key bytes>
    if(buffer[0] === 0xe7 && buffer[1] === 0x01) {
      const Secp256k1KeyPair = require('secp256k1-key-pair');
      return new Secp256k1KeyPair({
        publicKeyBase58: base58.encode(buffer.slice(2))
      });
    }

    throw new Error(`Unsupported Fingerprint Type: ${fingerprint}`);
  }
```

and ...


```
static async generate(options) {
    switch(options.type) {
      case 'Ed25519VerificationKey2018':
        const Ed25519KeyPair = require('./Ed25519KeyPair');
        return Ed25519KeyPair.generate(options);

      case 'EcdsaSecp256k1VerificationKey2019':
          const Secp256k1KeyPair = require('secp256k1-key-pair');
          return Secp256k1KeyPair.generate(options);

      case 'RsaVerificationKey2018':
        const RSAKeyPair = require('./RSAKeyPair');
        return RSAKeyPair.generate(options);

      default:
        throw new Error(`Unsupported Key Type: ${options.type}`);
    }
  }
```

You are currently bundling both RSA and Ed25519 in this library... technically you are bundling everything in `node-forge`, as there is no webpack or browserify build.

should these static methods take the key class as an argument? or should they just be removed, since your intention is not to bundle crypto in this library?

**Comment by OR13** [comment]
With guidance on addressing these static methods, I can implement these changes you have requested.

**Comment by mattcollier** [comment]
@dmitrizagidulin can you work with @OR13 on getting this moving?

**Comment by dmitrizagidulin** [comment]
@mattcollier I absolutely can, but this is more a policy decision, of whether we're including this key type in this library, or if we're absolutely requiring them in a separate lib. @dlongley ?

**Comment by dlongley** [comment]
> ...of whether we're including this key type in this library...

I'd prefer us to move to where each key type can be installed separately so you have the option to only install what you need. The core library shouldn't bring anything in automatically (but the README may give common examples). In that vein, we shouldn't add anything new here, but establish clear patterns for how to use it with the core lib and update the README. As we get time, we should move specific key types out into their own libs (so we shouldn't be adding to that future work load).

**Comment by OR13** [comment]
In order to support these key types in this library, this comment needs to be addressed: https://github.com/digitalbazaar/crypto-ld/pull/41#issuecomment-602093116

> should these static methods take the key class as an argument? or should they just be removed, since your intention is not to bundle crypto in this library?

I think an answer to this question is all that is needed to not bundle secp256k1 here, but still support it in crypto-ld.

**Comment by dlongley** [comment]
@dmitrizagidulin I'm +1 for removing those static methods -- are they really buying us much? They just seem to create an indirection and binding we don't need or want to have to maintain.

**Comment by dmitrizagidulin** [comment]
@OR13 - thank you again for adding support for the secp256k1 key type.
We're currently in the process of refactoring this library to remove the currently bundled Ed25519 and RSA key types (in PR #47), so each type will need to be selected/installed separately (this will include secp256k1).
I recommend that this PR can be closed.

**Comment by OR13** [comment]
Closing pending #47

**Pull request closed without merging**
